2024-10-30 16:15:56,011 ERROR: Exception on /admin/source/new/ [GET] [in /home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/base.py", line 369, in _run_view
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/model/base.py", line 2124, in create_view
    return self.render(template,
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/model/create.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/app/templates/admin/master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/base.html", line 39, in top-level template code
    {% block page_body %}
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/base.html", line 75, in block 'page_body'
    {% block body %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/model/create.html", line 22, in block 'body'
    {% block create_form %}
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/model/create.html", line 23, in block 'create_form'
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/lib.html", line 240, in template
    {% call form_tag(action=action) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/lib.html", line 209, in template
    {{ caller() }}
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/lib.html", line 241, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/lib.html", line 201, in template
    {{ render_field(form, f, kwargs) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/templates/bootstrap4/admin/lib.html", line 146, in template
    {{ field(**kwargs) | safe }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/wtforms/fields/core.py", line 164, in __call__
    return self.meta.render_field(self, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/Documents/Dev/zanah-news/backend/venv/lib/python3.12/site-packages/wtforms/widgets/core.py", line 374, in __call__
    val, label, selected, render_kw = choice
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)
